import pytest
from py2rust.backend.rust_codegen import RustCodegen
from py2rust.ir.ir_nodes import (
    IRModule, IRFunction, IRIntType, IRReturn,
    IRDictType, IRStrType, IRFileType, IRName
)

def test_codegen_lean_output():
    """Verify that unused features are not emitted in the generated Rust code."""
    # Simple function returning 0
    func = IRFunction(
        name="simple",
        params=(),
        return_type=IRIntType(),
        body=(IRReturn(value=IRName(name="0"), result_type=IRIntType()),)
    )
    mod = IRModule(functions=(func,), classes=())
    
    codegen = RustCodegen()
    output = codegen.generate(mod)
    
    assert "use std::collections::HashMap;" not in output
    assert "struct FileHandle" not in output
    # PyError is currently always emitted if there are functions because functions return Result<T, PyError>
    assert "pub enum PyError" in output 

def test_codegen_includes_hashmap_when_used():
    """Verify that HashMap is included when a dictionary is used."""
    func = IRFunction(
        name="use_dict",
        params=(),
        return_type=IRDictType(IRStrType(), IRIntType()),
        body=()
    )
    mod = IRModule(functions=(func,), classes=())
    
    codegen = RustCodegen()
    output = codegen.generate(mod)
    
    assert "use std::collections::HashMap;" in output

def test_codegen_includes_file_handle_when_used():
    """Verify that FileHandle and file imports are included when files are used."""
    func = IRFunction(
        name="use_file",
        params=(),
        return_type=IRFileType(),
        body=()
    )
    mod = IRModule(functions=(func,), classes=())
    
    codegen = RustCodegen()
    output = codegen.generate(mod)
    
    assert "struct FileHandle" in output
    assert "use std::fs::{File, OpenOptions};" in output
    assert "use std::io" in output

def test_codegen_no_header_padding_when_no_imports():
    """Verify that there is no extra newline if no imports are needed."""
    mod = IRModule(functions=(), classes=())
    
    codegen = RustCodegen()
    output = codegen.generate(mod)
    
    assert output == "// Generated by py2rust\n"
