// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<PyError> for pyo3::PyErr {
    fn from(err: PyError) -> Self {
        match err {
            PyError::Exception(s) => pyo3::exceptions::PyException::new_err(s),
            PyError::ValueError(s) => pyo3::exceptions::PyValueError::new_err(s),
            PyError::TypeError(s) => pyo3::exceptions::PyTypeError::new_err(s),
            PyError::KeyError(s) => pyo3::exceptions::PyKeyError::new_err(s),
            PyError::IndexError(s) => pyo3::exceptions::PyIndexError::new_err(s),
            PyError::IOError(s) => pyo3::exceptions::PyOSError::new_err(s),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum Color {
    RED,
    GREEN,
    BLUE,
}


fn describe_color(c: Color) -> Result<(), PyError> {
    match c {
        Color::RED => {
            println!("{}", "It is red".to_string());
        },
        Color::GREEN => {
            println!("{}", "It is green".to_string());
        },
        Color::BLUE => {
            println!("{}", "It is blue".to_string());
        },
        _ => {
            println!("{}", "Unknown color".to_string());
        },
    }
    Ok(())
}

fn check_value(x: i32) -> Result<(), PyError> {
    match x {
        1 => {
            println!("{}", "One".to_string());
        },
        2 => {
            println!("{}", "Two".to_string());
        },
        y => {
            println!("{}", "Other value".to_string());
        },
    }
    Ok(())
}

fn __py_main() -> Result<(), PyError> {
    describe_color(Color::RED)?;
    describe_color(Color::GREEN)?;
    check_value(1)?;
    check_value(2)?;
    check_value(3)?;
    Ok(())
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}



/*
[dependencies]
csv = { version = "1.1" }
pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
pythonize = { version = "0.20" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
*/
