// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum StrOrIntUnion {
    Str(String),
    Int(i32),
}

pub fn describe_number(x: Option<i32>) -> Result<String, PyError> {
    if x.is_none() {
        return Ok("Nothing".to_string());
    } else {
        return Ok(format!(
            "Number: {}",
            x.as_ref()
                .map(|v| format!("{}", v))
                .unwrap_or("None".to_string())
        ));
    }
    Ok(String::new())
}

pub fn combine(x: StrOrIntUnion) -> Result<String, PyError> {
    if matches!(x, StrOrIntUnion::Int(_)) {
        return Ok(format!("Int: {:?}", x));
    } else if matches!(x, StrOrIntUnion::Str(_)) {
        return Ok(format!("Str: {:?}", x));
    }
    return Ok("Unknown".to_string());
}

pub fn __py_main() -> Result<(), PyError> {
    println!("{}", describe_number(Some(10))?);
    println!("{}", describe_number(None)?);
    println!("{}", combine(StrOrIntUnion::Int(42))?);
    println!("{}", combine(StrOrIntUnion::Str("hello".to_string()))?);
    Ok(())
}
fn main() -> Result<(), PyError> {
    __py_main()?;

    Ok(())
}
