// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum Color {
    RED,
    GREEN,
    BLUE,
}

pub fn describe_color(c: Color) -> Result<(), PyError> {
    match c {
        Color::RED => {
            println!("{}", "It is red".to_string());
        }
        Color::GREEN => {
            println!("{}", "It is green".to_string());
        }
        Color::BLUE => {
            println!("{}", "It is blue".to_string());
        }
        _ => {
            println!("{}", "Unknown color".to_string());
        }
    }
    Ok(())
}

pub fn check_value(x: i32) -> Result<(), PyError> {
    match x {
        1 => {
            println!("{}", "One".to_string());
        }
        2 => {
            println!("{}", "Two".to_string());
        }
        y => {
            println!("{}", "Other value".to_string());
        }
    }
    Ok(())
}

pub fn __py_main() -> Result<(), PyError> {
    describe_color(Color::RED)?;
    describe_color(Color::GREEN)?;
    check_value(1)?;
    check_value(2)?;
    check_value(3)?;
    Ok(())
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}
