// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

// Using tokio as async runtime


pub async fn say_hello(name: String) -> Result<String, PyError> {
    return Ok("Hello, ".to_string().to_string() + &name);
}

pub async fn calculate(a: i32, b: i32) -> Result<i32, PyError> {
    return Ok(a + b);
}

pub async fn __py_main() -> Result<(), PyError> {
    let msg: String = say_hello("Async World".to_string()).await?;
    println!("{}", msg);
    let val: i32 = calculate(10, 20).await?;
    println!("{}", "Result:".to_string());
    println!("{}", val);
    Ok(())
}
#[tokio::main]
async fn main() -> Result<(), PyError> {
    __py_main().await?;
    Ok(())
}
