// Generated by py2rust
#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

#[derive(Clone, Debug)]
struct Counter {
    count: i32,
}

impl Counter {
    fn increment(&mut self) -> Result<(), PyError> {
        self.count = self.count + 1;
        Ok(())
    }
    fn get_count(&self) -> Result<i32, PyError> {
        return Ok(self.count);
    }
    fn new() -> Result<Self, PyError> {
        Ok(Self { count: 0 })
    }
}

fn main() -> Result<(), PyError> {
    let mut c: Counter = Counter::new()?;
    c.increment()?;
    c.increment()?;
    c.increment()?;
    let result: i32 = c.get_count()?;
    println!("{}", result);
    { 0; return Ok(()); }
}
