// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

#[derive(Clone, Debug)]
pub struct Point {
    pub x: i32,
    pub y: i32,
}

impl Point {
    pub fn new(x: i32, y: i32) -> Result<Self, PyError> {
        Ok(Self { x: x, y: y })
    }
    pub fn get_x(&self) -> Result<i32, PyError> {
        return Ok(self.x);
    }
    pub fn get_y(&self) -> Result<i32, PyError> {
        return Ok(self.y);
    }
    pub fn distance_to(&self, other_x: i32) -> Result<i32, PyError> {
        let dx: i32 = self.x - other_x;
        return Ok(dx);
    }
}

pub fn __py_main() -> Result<(), PyError> {
    let p: Point = Point::new(3, 4)?;
    let x: i32 = p.get_x()?;
    let y: i32 = p.get_y()?;
    let d: i32 = p.distance_to(0)?;
    return Ok({
        (x + y) + d;
        ()
    });
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}
