// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

#[derive(Clone, Debug)]
pub struct Counter {
    pub count: i32,
}

impl Counter {
    pub fn new() -> Result<Self, PyError> {
        Ok(Self { count: 0 })
    }
    pub fn increment(&mut self) -> Result<(), PyError> {
        self.count = self.count + 1;
        Ok(())
    }
    pub fn get_count(&self) -> Result<i32, PyError> {
        return Ok(self.count);
    }
}

pub fn __py_main() -> Result<(), PyError> {
    let mut c: Counter = Counter::new()?;
    c.increment()?;
    c.increment()?;
    c.increment()?;
    let result: i32 = c.get_count()?;
    println!("{}", result);
    return Ok(());
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}
