// Generated by py2rust
#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

#[derive(Clone, Debug)]
struct Point {
    x: i32,
    y: i32,
}

impl Point {
    fn get_x(&self) -> Result<i32, PyError> {
        return Ok(self.x);
    }
    fn get_y(&self) -> Result<i32, PyError> {
        return Ok(self.y);
    }
    fn distance_to(&self, other_x: i32) -> Result<i32, PyError> {
        let dx: i32 = (self.x - other_x);
        return Ok(dx);
    }
    fn new(x: i32, y: i32) -> Result<Self, PyError> {
        Ok(Self { x: x, y: y })
    }
}

fn main() -> Result<(), PyError> {
    let p: Point = Point::new(3, 4)?;
    let x: i32 = p.get_x()?;
    let y: i32 = p.get_y()?;
    let d: i32 = p.distance_to(0)?;
    { ((x + y) + d); return Ok(()); }
}
