// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<PyError> for pyo3::PyErr {
    fn from(err: PyError) -> Self {
        match err {
            PyError::Exception(s) => pyo3::exceptions::PyException::new_err(s),
            PyError::ValueError(s) => pyo3::exceptions::PyValueError::new_err(s),
            PyError::TypeError(s) => pyo3::exceptions::PyTypeError::new_err(s),
            PyError::KeyError(s) => pyo3::exceptions::PyKeyError::new_err(s),
            PyError::IndexError(s) => pyo3::exceptions::PyIndexError::new_err(s),
            PyError::IOError(s) => pyo3::exceptions::PyOSError::new_err(s),
        }
    }
}

pub trait ATrait {
    fn greet(&self) -> Result<String, PyError>;
}

pub trait BTrait: ATrait {
    fn specific_b(&self) -> Result<String, PyError>;
}

pub trait CTrait: ATrait {
    fn specific_c(&self) -> Result<String, PyError>;
}

pub trait DTrait: BTrait + CTrait {
}

#[derive(Clone, Debug)]
struct A {
}

impl A {
    fn new() -> Result<Self, PyError> {
        Ok(Self {  })
    }
}

impl ATrait for A {
    fn greet(&self) -> Result<String, PyError> {
        return Ok("A".to_string());
    }
}


#[derive(Clone, Debug)]
struct B {
}

impl B {
    fn new() -> Result<Self, PyError> {
        Ok(Self {  })
    }
}

impl BTrait for B {
    fn specific_b(&self) -> Result<String, PyError> {
        return Ok("Specific B".to_string());
    }
}

impl ATrait for B {
    fn greet(&self) -> Result<String, PyError> {
        return Ok("B".to_string());
    }
}


#[derive(Clone, Debug)]
struct C {
}

impl C {
    fn new() -> Result<Self, PyError> {
        Ok(Self {  })
    }
}

impl CTrait for C {
    fn specific_c(&self) -> Result<String, PyError> {
        return Ok("Specific C".to_string());
    }
}

impl ATrait for C {
    fn greet(&self) -> Result<String, PyError> {
        return Ok("C".to_string());
    }
}


#[derive(Clone, Debug)]
struct D {
}

impl D {
    fn new() -> Result<Self, PyError> {
        Ok(Self {  })
    }
}

impl DTrait for D {
}

impl BTrait for D {
    fn specific_b(&self) -> Result<String, PyError> {
        return Ok("Specific B".to_string());
    }
}

impl CTrait for D {
    fn specific_c(&self) -> Result<String, PyError> {
        return Ok("Specific C".to_string());
    }
}

impl ATrait for D {
    fn greet(&self) -> Result<String, PyError> {
        return Ok("D".to_string());
    }
}


fn __py_main() -> Result<(), PyError> {
    let d: D = D::new()?;
    println!("{}", d.greet()?);
    println!("{}", d.specific_b()?);
    println!("{}", d.specific_c()?);
    return Ok({ 0; () });
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}



/*
[dependencies]
csv = { version = "1.1" }
pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
pythonize = { version = "0.20" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
*/
