// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<PyError> for pyo3::PyErr {
    fn from(err: PyError) -> Self {
        match err {
            PyError::Exception(s) => pyo3::exceptions::PyException::new_err(s),
            PyError::ValueError(s) => pyo3::exceptions::PyValueError::new_err(s),
            PyError::TypeError(s) => pyo3::exceptions::PyTypeError::new_err(s),
            PyError::KeyError(s) => pyo3::exceptions::PyKeyError::new_err(s),
            PyError::IndexError(s) => pyo3::exceptions::PyIndexError::new_err(s),
            PyError::IOError(s) => pyo3::exceptions::PyOSError::new_err(s),
        }
    }
}

pub trait PointTrait {
    fn __str__(&self) -> Result<String, PyError>;
}

#[derive(Clone, Debug)]
struct Point {
    x: i32,
    y: i32,
}

impl Point {
    fn new(x: i32, y: i32) -> Result<Self, PyError> {
        Ok(Self { x: x, y: y })
    }
}

impl PointTrait for Point {
    fn __str__(&self) -> Result<String, PyError> {
        return Ok(format!("({}, {})", self.x, self.y));
    }
}

impl std::fmt::Display for Point {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.__str__() {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}


fn __py_main() -> Result<(), PyError> {
    let p: Point = Point::new(1, 2)?;
    let s: String = p.__str__()?;
    println!("{}", s);
    let num_str: String = "42".to_string();
    let num: i32 = num_str.parse::<i32>().map_err(|e| PyError::ValueError(e.to_string()))?;
    println!("{}", num);
    Ok(())
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}



/*
[dependencies]
csv = { version = "1.1" }
pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
pythonize = { version = "0.20" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
*/
