// Generated by py2rust
#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

pub trait ContainerTrait {
    fn __getitem__(&self, idx: i32) -> Result<i32, PyError>;
    fn __setitem__(&mut self, idx: i32, val: i32) -> Result<(), PyError>;
}

#[derive(Clone, Debug)]
struct Container {
    items: Vec<i32>,
}

impl Container {
    fn new() -> Result<Self, PyError> {
        Ok(Self { items: vec![0].repeat(3 as usize) })
    }
}

impl ContainerTrait for Container {
    fn __getitem__(&self, idx: i32) -> Result<i32, PyError> {
        return Ok({ let __coll = &(self.items); let __idx_raw = idx; let actual_idx = if __idx_raw < 0 { (__idx_raw + (__coll.len() as i32) as i32) as usize } else { __idx_raw as usize }; __coll[actual_idx] });
    }
    fn __setitem__(&mut self, idx: i32, val: i32) -> Result<(), PyError> {
        self.items[idx as usize] = val;
        Ok(())
    }
}


fn test() -> Result<(), PyError> {
    let mut c: Container = Container::new()?;
    c.__setitem__(1, 10)?;
    println!("{}", c.__getitem__(1)?);
    Ok(())
}

fn main() -> Result<(), PyError> {
    test()?;
    Ok(())
}
