// Generated by py2rust
#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

pub trait PointTrait {
    fn __add__(&self, other: Point) -> Result<Point, PyError>;
    fn __sub__(&self, other: Point) -> Result<Point, PyError>;
    fn __mul__(&self, factor: i32) -> Result<Point, PyError>;
    fn __eq__(&self, other: Point) -> Result<bool, PyError>;
    fn __lt__(&self, other: Point) -> Result<bool, PyError>;
    fn __str__(&self) -> Result<String, PyError>;
}

#[derive(Clone, Debug)]
struct Point {
    x: i32,
    y: i32,
}

impl Point {
    fn new(x: i32, y: i32) -> Result<Self, PyError> {
        Ok(Self { x: x, y: y })
    }
}

impl PointTrait for Point {
    fn __add__(&self, other: Point) -> Result<Point, PyError> {
        return Ok(Point::new((self.x + other.x), (self.y + other.y))?);
    }
    fn __sub__(&self, other: Point) -> Result<Point, PyError> {
        return Ok(Point::new((self.x - other.x), (self.y - other.y))?);
    }
    fn __mul__(&self, factor: i32) -> Result<Point, PyError> {
        return Ok(Point::new((self.x * factor), (self.y * factor))?);
    }
    fn __eq__(&self, other: Point) -> Result<bool, PyError> {
        return Ok((self.x == other.x && self.y == other.y));
    }
    fn __lt__(&self, other: Point) -> Result<bool, PyError> {
        if self.x != other.x {
            return Ok(self.x < other.x);
        }
        return Ok(self.y < other.y);
    }
    fn __str__(&self) -> Result<String, PyError> {
        return Ok(format!("Point({}, {})", self.x, self.y));
    }
}

impl std::fmt::Display for Point {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.__str__() {
            Ok(s) => write!(f, "{}", s),
            Err(_) => Err(std::fmt::Error),
        }
    }
}

impl std::ops::Add<Point> for Point {
    type Output = Point;
    fn add(self, rhs: Point) -> Self::Output {
        self.__add__(rhs).unwrap()
    }
}

impl std::ops::Sub<Point> for Point {
    type Output = Point;
    fn sub(self, rhs: Point) -> Self::Output {
        self.__sub__(rhs).unwrap()
    }
}

impl std::ops::Mul<i32> for Point {
    type Output = Point;
    fn mul(self, rhs: i32) -> Self::Output {
        self.__mul__(rhs).unwrap()
    }
}

impl PartialEq<Point> for Point {
    fn eq(&self, other: &Point) -> bool {
        self.__eq__(other.clone()).unwrap_or(false)
    }
}

impl PartialOrd<Point> for Point {
    fn partial_cmp(&self, other: &Point) -> Option<std::cmp::Ordering> {
        if self.__lt__(other.clone()).unwrap_or(false) {
            Some(std::cmp::Ordering::Less)
        } else if self == other {
            Some(std::cmp::Ordering::Equal)
        } else {
            Some(std::cmp::Ordering::Greater)
        }
    }
}


fn main() -> Result<(), PyError> {
    let p1: Point = Point::new(10, 20)?;
    let p2: Point = Point::new(5, 5)?;
    let p3: Point = (p1.clone() + p2.clone());
    let p4: Point = (p1.clone() - p2.clone());
    println!("{}", p3);
    println!("{}", p4);
    if p1.clone() == p2.clone() {
        println!("{}", "Equal".to_string());
    } else {
        println!("{}", "Not Equal".to_string());
    }
    let p5: Point = Point::new(10, 20)?;
    if p1.clone() == p5.clone() {
        println!("{}", "p1 == p5".to_string());
    }
    if p2.clone() < p1.clone() {
        println!("{}", "p2 < p1".to_string());
    } else {
        println!("{}", "p2 >= p1".to_string());
    }
    if p1.clone() > p2.clone() {
        println!("{}", "p1 > p2".to_string());
    }
    let p6: Point = (p1.clone() * 2);
    println!("{}", p6);
    let p7: Point = (p1.clone() + p2.clone());
    let p8: Point = (p7.clone() - p2.clone());
    if p8.clone() == p1.clone() {
        println!("{}", "p8 == p1".to_string());
    }
    Ok(())
}
