// Generated by py2rust
#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

fn divide(a: i32, b: i32) -> Result<i32, PyError> {
    if b == 0 {
        return Err(PyError::ValueError("Division by zero".to_string()));
    }
    return Ok(((a as f64 / b as f64).floor() as i32));
}

fn main() -> Result<(), PyError> {
    {
        let __result = (|| -> Result<(), PyError> {
            let x: i32 = divide(10, 0)?;
            println!("{}", x);
            Ok(())
        })();
        if let Err(__exc) = __result {
            println!("{}", (-(1)));
        }
    }
    {
        let __result = (|| -> Result<(), PyError> {
            let y: i32 = divide(10, 2)?;
            println!("{}", y);
            Ok(())
        })();
        if let Err(__exc) = __result {
            println!("{}", (-(2)));
        }
    }
    { 0; return Ok(()); }
}
