// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<PyError> for pyo3::PyErr {
    fn from(err: PyError) -> Self {
        match err {
            PyError::Exception(s) => pyo3::exceptions::PyException::new_err(s),
            PyError::ValueError(s) => pyo3::exceptions::PyValueError::new_err(s),
            PyError::TypeError(s) => pyo3::exceptions::PyTypeError::new_err(s),
            PyError::KeyError(s) => pyo3::exceptions::PyKeyError::new_err(s),
            PyError::IndexError(s) => pyo3::exceptions::PyIndexError::new_err(s),
            PyError::IOError(s) => pyo3::exceptions::PyOSError::new_err(s),
        }
    }
}

pub enum TryResult<T> {
    Normal,
    Return(T),
    Break,
    Continue,
}

fn divide(a: i32, b: i32) -> Result<i32, PyError> {
    if b == 0 {
        return Err(PyError::ValueError("Division by zero".to_string()));
    }
    return Ok((a as f64 / b as f64).floor() as i32);
}

fn __py_main() -> Result<(), PyError> {
    let mut y: i32 = 0;
    let mut x: i32 = 0;

    {
        let __result = (|| -> Result<TryResult<()>, PyError> {
            x = divide(10, 0)?;
            println!("{}", x);
            Ok(TryResult::Normal)
        })();
        match __result {
            Ok(TryResult::Return(v)) => return Ok(v),
            Ok(TryResult::Break) => panic!("break outside loop"),
            Ok(TryResult::Continue) => panic!("continue outside loop"),
            Ok(TryResult::Normal) => {}
            Err(_) => {
                println!("{}", (-(1)));
            }
        }
    }
    {
        let __result = (|| -> Result<TryResult<()>, PyError> {
            y = divide(10, 2)?;
            println!("{}", y);
            Ok(TryResult::Normal)
        })();
        match __result {
            Ok(TryResult::Return(v)) => return Ok(v),
            Ok(TryResult::Break) => panic!("break outside loop"),
            Ok(TryResult::Continue) => panic!("continue outside loop"),
            Ok(TryResult::Normal) => {}
            Err(_) => {
                println!("{}", (-(2)));
            }
        }
    }
    return Ok({ 0; () });
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}



/*
[dependencies]
csv = { version = "1.1" }
pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
pythonize = { version = "0.20" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
*/
