// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<PyError> for pyo3::PyErr {
    fn from(err: PyError) -> Self {
        match err {
            PyError::Exception(s) => pyo3::exceptions::PyException::new_err(s),
            PyError::ValueError(s) => pyo3::exceptions::PyValueError::new_err(s),
            PyError::TypeError(s) => pyo3::exceptions::PyTypeError::new_err(s),
            PyError::KeyError(s) => pyo3::exceptions::PyKeyError::new_err(s),
            PyError::IndexError(s) => pyo3::exceptions::PyIndexError::new_err(s),
            PyError::IOError(s) => pyo3::exceptions::PyOSError::new_err(s),
        }
    }
}

fn first_element<T: Clone>(items: Vec<T>) -> Result<T, PyError> {
    return Ok({ let __coll = &(items); let __idx_raw = 0; let actual_idx = if __idx_raw < 0 { (__idx_raw + (__coll.len() as i32) as i32) as usize } else { __idx_raw as usize }; __coll[actual_idx].clone() });
}

fn __py_main() -> Result<(), PyError> {
    let nums: Vec<i32> = vec![1, 2, 3];
    let strs: Vec<String> = vec!["a".to_string(), "b".to_string(), "c".to_string()];
    println!("{}", first_element(nums)?);
    println!("{}", first_element(strs)?);
    Ok(())
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}



/*
[dependencies]
csv = { version = "1.1" }
pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
pythonize = { version = "0.20" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
*/
