// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

use std::collections::HashMap;
use std::collections::HashSet;

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

fn __py_main() -> Result<(), PyError> {
    let add: _ = |x, y| { (x + y) };
    println!("{}", add(10, 20));
    let nums: Vec<i32> = vec![1, 2, 3, 4, 5, 6];
    let evens: Vec<i32> = { let mut __res = Vec::<i32>::new(); for &x in &nums { if (x % 2) == 0 { __res.push(x);  }  }  __res };
    println!("{:?}", evens);
    let squares: Vec<i32> = { let mut __res = Vec::<i32>::new(); for &x in &nums { __res.push((x * x));  }  __res };
    println!("{:?}", squares);
    let xs: Vec<i32> = vec![1, 2];
    let ys: Vec<i32> = vec![10, 20];
    let pairs: Vec<(i32, i32)> = { let mut __res = Vec::<(i32, i32)>::new(); for &x in &xs { for &y in &ys { __res.push((x, y));  }  }  __res };
    println!("{:?}", pairs);
    let unique_nums: HashSet<i32> = { let mut __res = HashSet::<i32>::new(); for &x in &nums { __res.insert((x % 3));  }  __res };
    println!("{}", unique_nums.len() as i32);
    let mapping: HashMap<i32, i32> = { let mut __res = HashMap::<i32, i32>::new(); for &x in &nums { if x < 4 { __res.insert(x, (x * 10));  }  }  __res };
    println!("{:?}", mapping);
    return Ok(());
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}
