// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<PyError> for pyo3::PyErr {
    fn from(err: PyError) -> Self {
        match err {
            PyError::Exception(s) => pyo3::exceptions::PyException::new_err(s),
            PyError::ValueError(s) => pyo3::exceptions::PyValueError::new_err(s),
            PyError::TypeError(s) => pyo3::exceptions::PyTypeError::new_err(s),
            PyError::KeyError(s) => pyo3::exceptions::PyKeyError::new_err(s),
            PyError::IndexError(s) => pyo3::exceptions::PyIndexError::new_err(s),
            PyError::IOError(s) => pyo3::exceptions::PyOSError::new_err(s),
        }
    }
}

fn __py_main() -> Result<(), PyError> {
    let mut n: i32 = 0;
    let mut r: i32 = 0;
    let mut i: i32 = 0;
    let mut d: i32 = 0;
    let mut c: String = String::new();

    let nums: Vec<i32> = vec![1, 2, 3];
    let chars: Vec<String> = vec!["a".to_string(), "b".to_string(), "c".to_string()];
    {
        '__loop_0: for __loop_val in (&nums).iter().zip((&chars).iter()) {
            let (__tmp_0, __tmp_1) = __loop_val.clone();
            n = __tmp_0.clone();
            c = __tmp_1.clone();
            println!("{}", n);
            println!("{}", c);
        }
    }
    {
        '__loop_0: for __loop_val in (&nums).iter().enumerate().map(|(i, x)| (i as i32, x)) {
            let (__tmp_0, __tmp_1) = __loop_val.clone();
            i = __tmp_0.clone();
            n = __tmp_1.clone();
            println!("{}", i);
            println!("{}", n);
        }
    }
    let doubled: Vec<i32> = (&nums).iter().map(|x| { (x * 2) }).collect::<Vec<_>>();
    {
        '__loop_0: for __loop_val in &doubled {
            d = __loop_val.clone();
            println!("{}", d);
        }
    }
    {
        '__loop_0: for __loop_val in (&nums).iter().rev() {
            r = __loop_val.clone();
            println!("{}", r);
        }
    }
    return Ok({ 0; () });
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}



/*
[dependencies]
csv = { version = "1.1" }
pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
pythonize = { version = "0.20" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
*/
