// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
//

use std::collections::HashMap;
use std::fs::{File, OpenOptions};
use std::io::{self, Read, Write, BufRead, BufReader, Seek, SeekFrom};
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList, PyTuple};
use serde_json;
use pythonize;
use csv;

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

struct FileHandle {
    file: File,
}

impl FileHandle {
    fn open(path: &str, mode: &str) -> std::io::Result<Self> {
        let file = match mode {
            "r" => File::open(path)?,
            "w" => File::create(path)?,
            "a" => OpenOptions::new().append(true).open(path)?,
            "rb" => File::open(path)?,
            "wb" => File::create(path)?,
            "ab" => OpenOptions::new().append(true).open(path)?,
            _ => File::open(path)?,
        };
        Ok(FileHandle { file })
    }

    fn read(&mut self) -> std::io::Result<String> {
        let mut contents = String::new();
        self.file.read_to_string(&mut contents)?;
        Ok(contents)
    }

    fn readline(&mut self) -> std::io::Result<String> {
        let mut reader = BufReader::new(&self.file);
        let mut line = String::new();
        reader.read_line(&mut line)?;
        Ok(line)
    }

    fn write(&mut self, content: &str) -> std::io::Result<()> {
        self.file.write_all(content.as_bytes())
    }

    fn close(self) -> std::io::Result<()> {
        Ok(())
    }

    fn tell(&mut self) -> std::io::Result<u64> {
        self.file.stream_position()
    }

    fn seek(&mut self, pos: u64) -> std::io::Result<u64> {
        self.file.seek(SeekFrom::Start(pos))
    }
}

fn test_json() -> Result<(), PyError> {
    let mut k: i32 = 0;

    println!("{}", "Testing JSON support...".to_string());
    let data: ExternalObject = ExternalObject::new(Python::with_gil(|py| { let d = PyDict::new(py); d.set_item("a".to_string(), 1).unwrap(); d.set_item("b".to_string(), vec![1, 2, 3]).unwrap(); d.set_item("c".to_string(), HashMap::from([("d".to_string(), true)])).unwrap(); d.to_object(py) }));
    let s: String = Python::with_gil(|py| { let val = pythonize::pythonize(data.obj.as_ref(py)).map_err(|e| PyError::ValueError(e.to_string()))?; let s = serde_json::to_string(&val).map_err(|e| PyError::ValueError(e.to_string()))?; Ok(s) })?;
    println!("{} {}", "Serialized:".to_string(), s);
    let mut data2: ExternalObject = Python::with_gil(|py| { let v: serde_json::Value = serde_json::from_str(&s).map_err(|e| PyError::ValueError(e.to_string()))?; let obj = pythonize::depythonize(py, &v).map_err(|e| PyError::ValueError(e.to_string()))?; Ok(ExternalObject::new(obj)) })?;
    println!("{} {}", "Deserialized 'a':".to_string(), data2.getitem("a".to_string())?);
    println!("{} {}", "Deserialized 'b':".to_string(), data2.getitem("b".to_string())?);
    data2.setitem("a".to_string(), 42)?;
    println!("{} {}", "Updated 'a':".to_string(), data2.getitem("a".to_string())?);
    println!("{}", "Iterating over keys:".to_string());
    {
        '__loop_0: for __loop_val in data2.iter()? {
            k = __loop_val.clone();
            println!("{} {}", "Key:".to_string(), k);
        }
    }
    Ok(())
}

fn test_csv() -> Result<(), PyError> {
    let mut row: i32 = 0;

    println!("{}", "\nTesting CSV support...".to_string());
    let mut f1: FileHandle = FileHandle::open(&"test.csv".to_string(), &"w".to_string())?;
    f1.write(&"name,age\nalice,30\nbob,25\n".to_string())?;
    f1.close()?;
    let mut f2: FileHandle = FileHandle::open(&"test.csv".to_string(), &"r".to_string())?;
    let reader: ExternalObject = ExternalObject::new_csv_reader(f2)?;
    {
        '__loop_0: for __loop_val in reader.iter()? {
            row = __loop_val.clone();
            println!("{} {}", "Row:".to_string(), row);
        }
    }
    f2.close()?;
    Ok(())
}

fn test_attr() -> Result<(), PyError> {
    Ok(())
}
fn main() {
    if let Err(e) = _main() {
        eprintln!("Py2Rust Error: {}", e);
        std::process::exit(1);
    }
}

fn _main() -> Result<(), PyError> {
    test_json()?;
    
    test_csv()?;
    
    test_attr()?;
    
    Ok(())
}

#[derive(Clone)]
pub struct ExternalObject {
    pub obj: PyObject,
}

impl From<PyErr> for PyError {
    fn from(err: PyErr) -> Self {
        PyError::Exception(err.to_string())
    }
}

impl ExternalObject {
    pub fn new(obj: PyObject) -> Self {
        Self { obj }
    }

    pub fn load_module(module: &str) -> PyResult<Self> {
        Python::with_gil(|py| {
            Self::init_venv(py)?;
            let m = py.import(module)?;
            Ok(Self::new(m.to_object(py)))
        })
    }

    fn init_venv(py: Python<'_>) -> PyResult<()> {
        use std::env;
        if let Ok(venv) = env::var("PY2RUST_VENV") {
            let sys = py.import("sys")?;
            let path = sys.getattr("path")?;
            
            let venv_path = std::path::PathBuf::from(venv);
            #[cfg(target_os = "windows")]
            {
                let mut sp_path = venv_path.clone();
                sp_path.push("Lib");
                sp_path.push("site-packages");
                let sp_str = sp_path.to_string_lossy().to_string();
                path.call_method1("append", (sp_str,))?;
            }
            #[cfg(not(target_os = "windows"))]
            {
                let lib_dir = venv_path.join("lib");
                if let Ok(entries) = std::fs::read_dir(lib_dir) {
                    for entry in entries.flatten() {
                        let p = entry.path();
                        if p.is_dir() && p.file_name().unwrap_or_default().to_string_lossy().starts_with("python") {
                            let site_packages = p.join("site-packages");
                            if site_packages.exists() {
                                let sp_str = site_packages.to_string_lossy().to_string();
                                path.call_method1("append", (sp_str,))?;
                                break;
                            }
                        }
                    }
                }
            }
        }
        Ok(())
    }

    pub fn getattr(&self, name: &str) -> PyResult<Self> {
        Python::with_gil(|py| {
            let attr = self.obj.getattr(py, name)?;
            Ok(Self::new(attr.to_object(py)))
        })
    }

    pub fn call(&self, args: impl IntoPy<Py<PyTuple>>) -> PyResult<Self> {
        Python::with_gil(|py| {
            let res = self.obj.call1(py, args)?;
            Ok(Self::new(res.to_object(py)))
        })
    }

    pub fn call_method(&self, method: &str, args: impl IntoPy<Py<PyTuple>>) -> PyResult<Self> {
        Python::with_gil(|py| {
            let res = self.obj.call_method1(py, method, args)?;
            Ok(Self::new(res.to_object(py)))
        })
    }

    pub fn setattr(&self, name: &str, value: impl IntoPy<PyObject>) -> PyResult<()> {
        Python::with_gil(|py| {
            self.obj.as_ref(py).setattr(name, value)?;
            Ok(())
        })
    }

    pub fn setitem(&self, key: impl IntoPy<PyObject>, value: impl IntoPy<PyObject>) -> PyResult<()> {
        Python::with_gil(|py| {
            self.obj.as_ref(py).set_item(key, value)?;
            Ok(())
        })
    }

    pub fn getitem(&self, key: impl IntoPy<PyObject>) -> PyResult<Self> {
        Python::with_gil(|py| {
            let item = self.obj.as_ref(py).get_item(key)?;
            Ok(Self::new(item.to_object(py)))
        })
    }

    pub fn len(&self) -> usize {
        Python::with_gil(|py| {
            self.obj.as_ref(py).len().unwrap_or(0)
        })
    }

    pub fn iter(&self) -> PyResult<Vec<Self>> {
        Python::with_gil(|py| {
            let iter = self.obj.as_ref(py).iter()?;
            let mut res = Vec::new();
            for item in iter {
                res.push(Self::new(item?.to_object(py)));
            }
            Ok(res)
        })
    }

    pub fn new_csv_reader(file_obj: Self) -> PyResult<Self> {
        Python::with_gil(|py| {
            let read_method = file_obj.obj.getattr(py, "read")?;
            let content: String = read_method.call0(py)?.extract(py)?;
            let mut reader = csv::ReaderBuilder::new()
                .has_headers(false)
                .from_reader(content.as_bytes());
            let mut rows = Vec::new();
            for result in reader.records() {
                let record = result.map_err(|e| PyError::ValueError(e.to_string()))?;
                let row: Vec<String> = record.iter().map(|s| s.to_string()).collect();
                rows.push(row.to_object(py));
            }
            Ok(Self::new(rows.to_object(py)))
        })
    }
}

impl std::fmt::Display for ExternalObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        Python::with_gil(|py| {
            let s = self.obj.as_ref(py).str().and_then(|s| s.extract::<String>()).unwrap_or_else(|_| "<external object>".to_string());
            write!(f, "{}", s)
        })
    }
}

impl std::fmt::Debug for ExternalObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        Python::with_gil(|py| {
            let r = self.obj.as_ref(py).repr().map(|r| r.to_string()).unwrap_or_else(|_| "<external object>".to_string());
            write!(f, "{:?}", r)
        })
    }
}

impl IntoPy<PyObject> for ExternalObject {
    fn into_py(self, _py: Python<'_>) -> PyObject {
        self.obj
    }
}



/*
[dependencies]
pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
*/
