// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

use csv;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList, PyTuple};
use pythonize;
use serde_json;
use std::collections::HashMap;

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<PyError> for pyo3::PyErr {
    fn from(err: PyError) -> Self {
        match err {
            PyError::Exception(s) => pyo3::exceptions::PyException::new_err(s),
            PyError::ValueError(s) => pyo3::exceptions::PyValueError::new_err(s),
            PyError::TypeError(s) => pyo3::exceptions::PyTypeError::new_err(s),
            PyError::KeyError(s) => pyo3::exceptions::PyKeyError::new_err(s),
            PyError::IndexError(s) => pyo3::exceptions::PyIndexError::new_err(s),
            PyError::IOError(s) => pyo3::exceptions::PyOSError::new_err(s),
        }
    }
}

pub fn test_json() -> Result<(), PyError> {
    let mut k: ExternalObject = ExternalObject::default();

    println!("{}", "Testing JSON support...".to_string());
    let data: ExternalObject = ExternalObject::new(Python::with_gil(|py| {
        let d = PyDict::new(py);
        d.set_item("a".to_string(), 1).unwrap();
        d.set_item("b".to_string(), vec![1, 2, 3]).unwrap();
        d.set_item("c".to_string(), HashMap::from([("d".to_string(), true)]))
            .unwrap();
        d.to_object(py)
    }));
    let s: String = Python::with_gil(|py| -> Result<String, PyError> {
        let json = py.import("json")?;
        let res = json.getattr("dumps")?.call1((data.obj.as_ref(py),))?;
        Ok(res.extract()?)
    })?;
    println!("{} {}", "Serialized:".to_string(), s);
    let mut data2: ExternalObject = Python::with_gil(|py| -> Result<ExternalObject, PyError> {
        let v: serde_json::Value =
            serde_json::from_str(&s).map_err(|e| PyError::ValueError(e.to_string()))?;
        let obj = pythonize::pythonize(py, &v).map_err(|e| PyError::ValueError(e.to_string()))?;
        Ok(ExternalObject::new(obj))
    })?;
    println!(
        "{} {}",
        "Deserialized 'a':".to_string(),
        data2.getitem("a".to_string())?
    );
    println!(
        "{} {}",
        "Deserialized 'b':".to_string(),
        data2.getitem("b".to_string())?
    );
    data2.setitem("a".to_string(), 42)?;
    println!(
        "{} {}",
        "Updated 'a':".to_string(),
        data2.getitem("a".to_string())?
    );
    println!("{}", "Iterating over keys:".to_string());
    {
        '__loop_0: for __loop_val in data2.iter()? {
            k = __loop_val.clone();
            println!("{} {}", "Key:".to_string(), k);
        }
    }
    Ok(())
}

#[cfg(test)]
#[test]
fn _test_wrapper_test_json() {
    test_json().unwrap();
}

pub fn test_csv() -> Result<(), PyError> {
    let mut row: ExternalObject = ExternalObject::default();

    println!("{}", "\nTesting CSV support...".to_string());
    let mut f1: ExternalObject =
        ExternalObject::call_builtin("open", ("test.csv".to_string(), "w".to_string()))?;
    f1.write(&"name,age\nalice,30\nbob,25\n".to_string())?;
    f1.close()?;
    let mut f2: ExternalObject =
        ExternalObject::call_builtin("open", ("test.csv".to_string(), "r".to_string()))?;
    let reader: ExternalObject = ExternalObject::new_csv_reader(&f2)?;
    {
        '__loop_0: for __loop_val in reader.iter()? {
            row = __loop_val.clone();
            println!("{} {}", "Row:".to_string(), row);
        }
    }
    f2.close()?;
    Ok(())
}

#[cfg(test)]
#[test]
fn _test_wrapper_test_csv() {
    test_csv().unwrap();
}

pub fn test_attr() -> Result<(), PyError> {
    Ok(())
}

#[cfg(test)]
#[test]
fn _test_wrapper_test_attr() {
    test_attr().unwrap();
}
fn main() -> Result<(), PyError> {
    test_json()?;

    test_csv()?;

    test_attr()?;

    Ok(())
}

#[derive(Clone)]
pub struct ExternalObject {
    pub obj: PyObject,
}

impl From<PyErr> for PyError {
    fn from(err: PyErr) -> Self {
        PyError::Exception(err.to_string())
    }
}
impl Default for ExternalObject {
    fn default() -> Self {
        Python::with_gil(|py| Self::new(py.None()))
    }
}

impl ExternalObject {
    pub fn new(obj: PyObject) -> Self {
        Self { obj }
    }

    pub fn from_module(module: &str, name: &str) -> Self {
        Python::with_gil(|py| {
            let m = py.import(module).expect("Failed to import module");
            let attr = m
                .getattr(name)
                .expect("Failed to get attribute from module");
            Self::new(attr.to_object(py))
        })
    }

    pub fn load_module(module: &str) -> PyResult<Self> {
        Python::with_gil(|py| {
            Self::init_venv(py)?;
            let m = py.import(module)?;
            Ok(Self::new(m.to_object(py)))
        })
    }

    fn init_venv(py: Python<'_>) -> PyResult<()> {
        use std::env;
        if let Ok(venv) = env::var("PY2RUST_VENV") {
            let sys = py.import("sys")?;
            let path = sys.getattr("path")?;

            let venv_path = std::path::PathBuf::from(venv);
            #[cfg(target_os = "windows")]
            {
                let mut sp_path = venv_path.clone();
                sp_path.push("Lib");
                sp_path.push("site-packages");
                let sp_str = sp_path.to_string_lossy().to_string();
                path.call_method1("append", (sp_str,))?;
            }
            #[cfg(not(target_os = "windows"))]
            {
                let lib_dir = venv_path.join("lib");
                if let Ok(entries) = std::fs::read_dir(lib_dir) {
                    for entry in entries.flatten() {
                        let p = entry.path();
                        if p.is_dir()
                            && p.file_name()
                                .unwrap_or_default()
                                .to_string_lossy()
                                .starts_with("python")
                        {
                            let site_packages = p.join("site-packages");
                            if site_packages.exists() {
                                let sp_str = site_packages.to_string_lossy().to_string();
                                path.call_method1("append", (sp_str,))?;
                                break;
                            }
                        }
                    }
                }
            }
        }
        Ok(())
    }

    pub fn getattr(&self, name: &str) -> PyResult<Self> {
        Python::with_gil(|py| {
            let attr = self.obj.getattr(py, name)?;
            Ok(Self::new(attr.to_object(py)))
        })
    }

    pub fn call(&self, args: impl IntoPy<Py<PyTuple>>) -> PyResult<Self> {
        Python::with_gil(|py| {
            let res = self.obj.call1(py, args)?;
            Ok(Self::new(res.to_object(py)))
        })
    }

    pub fn call_method(&self, method: &str, args: impl IntoPy<Py<PyTuple>>) -> PyResult<Self> {
        Python::with_gil(|py| {
            let res = self.obj.call_method1(py, method, args)?;
            Ok(Self::new(res.to_object(py)))
        })
    }

    pub fn setattr(&self, name: &str, value: impl IntoPy<PyObject>) -> PyResult<()> {
        Python::with_gil(|py| {
            let value = value.into_py(py);
            self.obj.as_ref(py).setattr(name, value)?;
            Ok(())
        })
    }

    pub fn setitem(
        &self,
        key: impl IntoPy<PyObject>,
        value: impl IntoPy<PyObject>,
    ) -> PyResult<()> {
        Python::with_gil(|py| {
            let key = key.into_py(py);
            let value = value.into_py(py);
            self.obj.as_ref(py).set_item(key, value)?;
            Ok(())
        })
    }

    pub fn getitem(&self, key: impl IntoPy<PyObject>) -> PyResult<Self> {
        Python::with_gil(|py| {
            let key = key.into_py(py);
            let item = self.obj.as_ref(py).get_item(key)?;
            Ok(Self::new(item.to_object(py)))
        })
    }

    pub fn call_builtin(name: &str, args: impl IntoPy<Py<PyTuple>>) -> PyResult<Self> {
        Python::with_gil(|py| {
            let builtins = py.import("builtins")?;
            let func = builtins.getattr(name)?;
            let res = func.call1(args)?;
            Ok(Self::new(res.to_object(py)))
        })
    }

    pub fn read(&self) -> PyResult<String> {
        Python::with_gil(|py| {
            let res = self.obj.call_method0(py, "read")?;
            res.extract(py)
        })
    }

    pub fn write(&self, data: &str) -> PyResult<()> {
        Python::with_gil(|py| {
            self.obj.call_method1(py, "write", (data,))?;
            Ok(())
        })
    }

    pub fn close(&self) -> PyResult<()> {
        Python::with_gil(|py| {
            self.obj.call_method0(py, "close")?;
            Ok(())
        })
    }

    pub fn len(&self) -> usize {
        Python::with_gil(|py| self.obj.as_ref(py).len().unwrap_or(0))
    }

    pub fn iter(&self) -> PyResult<Vec<Self>> {
        Python::with_gil(|py| {
            let iter = self.obj.as_ref(py).iter()?;
            let mut res = Vec::new();
            for item in iter {
                res.push(Self::new(item?.to_object(py)));
            }
            Ok(res)
        })
    }

    pub fn new_csv_reader(file_obj: &Self) -> PyResult<Self> {
        Python::with_gil(|py| {
            let csv = py.import("csv")?;
            let reader = csv.getattr("reader")?.call1((file_obj.obj.as_ref(py),))?;
            Ok(Self::new(reader.to_object(py)))
        })
    }
}

impl std::fmt::Display for ExternalObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        Python::with_gil(|py| {
            let s = self
                .obj
                .as_ref(py)
                .str()
                .and_then(|s| s.extract::<String>())
                .unwrap_or_else(|_| "<external object>".to_string());
            write!(f, "{}", s)
        })
    }
}

impl std::fmt::Debug for ExternalObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        Python::with_gil(|py| {
            let r = self
                .obj
                .as_ref(py)
                .repr()
                .map(|r| r.to_string())
                .unwrap_or_else(|_| "<external object>".to_string());
            write!(f, "{:?}", r)
        })
    }
}

impl IntoPy<PyObject> for ExternalObject {
    fn into_py(self, _py: Python<'_>) -> PyObject {
        self.obj
    }
}
