// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

fn test_as() -> Result<(), PyError> {
    println!("{}", "math as m test".to_string());
    Ok(())
}

fn test_global_local() -> Result<(), PyError> {
    // WARNING: Python 'global' for [x] is not fully supported in Rust's ownership model.
    // It usually indicates shared state which should be handled via Arc<Mutex<T>> or passed as arguments.
    let x: i32 = 1;
    println!("{}", x);
    Ok(())
}

fn __py_main() -> Result<(), PyError> {
    test_as()?;
    test_global_local()?;
    Ok(())
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}



/*
[dependencies]
pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
*/
