// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

pub fn sum_list(nums: Vec<i32>) -> Result<i32, PyError> {
    let mut total: i32 = 0;
    let mut n: i32 = 0;

    total = 0;
    {
        for __i_n in 0..nums.len() as i32 {
            n = __i_n;
            total = (total + {
                let __coll = &(nums);
                let __idx_raw = n;
                let actual_idx = if __idx_raw < 0 {
                    (__idx_raw + (__coll.len() as i32) as i32) as usize
                } else {
                    __idx_raw as usize
                };
                __coll[actual_idx]
            });
        }
    }
    return Ok(total);
}

pub fn __py_main() -> Result<(), PyError> {
    let numbers: Vec<i32> = vec![1, 2, 3, 4, 5];
    let result: i32 = sum_list(numbers)?;
    println!("{}", result);
    return Ok(());
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}
