// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

use std::collections::HashMap;

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

pub fn __py_main() -> Result<(), PyError> {
    let lst: Vec<i32> = vec![1, 2, 3];
    if lst.contains(&1) {
        println!("{}", 100);
    }
    let d: HashMap<String, i32> = HashMap::from([("a".to_string(), 10), ("b".to_string(), 20)]);
    if d.contains_key(&"a".to_string()) {
        println!("{}", 200);
    }
    if !(d.contains_key(&"c".to_string())) {
        println!("{}", 300);
    }
    let s: String = "hello".to_string();
    if s.contains("h".to_string().as_str()) {
        println!("{}", 400);
    }
    return Ok(());
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}
