// Generated by py2rust
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList, PyTuple};

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

fn test_external() -> Result<(), PyError> {
    let cwd: ExternalObject = ExternalObject::load_module("os")?.call_method("getcwd", ())?;
    println!("{}", cwd);
    let parent: ExternalObject = ExternalObject::load_module("os")?.getattr("path")?.call_method("dirname", (cwd,))?;
    println!("{}", parent);
    Ok(())
}
test_external()?;


#[derive(Clone)]
pub struct ExternalObject {
    pub obj: PyObject,
}

impl ExternalObject {
    pub fn new(obj: PyObject) -> Self {
        Self { obj }
    }

    pub fn load_module(module: &str) -> PyResult<Self> {
        Python::with_gil(|py| {
            let m = py.import(module)?;
            Ok(Self::new(m.to_object(py)))
        })
    }

    pub fn getattr(&self, name: &str) -> PyResult<Self> {
        Python::with_gil(|py| {
            let attr = self.obj.getattr(py, name)?;
            Ok(Self::new(attr.to_object(py)))
        })
    }

    pub fn call(&self, args: impl IntoPy<Py<PyTuple>>) -> PyResult<Self> {
        Python::with_gil(|py| {
            let res = self.obj.call1(py, args)?;
            Ok(Self::new(res.to_object(py)))
        })
    }

    pub fn call_method(&self, method: &str, args: impl IntoPy<Py<PyTuple>>) -> PyResult<Self> {
        Python::with_gil(|py| {
            let res = self.obj.call_method1(py, method, args)?;
            Ok(Self::new(res.to_object(py)))
        })
    }
}

impl std::fmt::Display for ExternalObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        Python::with_gil(|py| {
            let s = self.obj.extract::<String>(py).unwrap_or_else(|_| "<external object>".to_string());
            write!(f, "{}", s)
        })
    }
}

impl std::fmt::Debug for ExternalObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        Python::with_gil(|py| {
            let r = self.obj.repr(py).map(|r| r.to_string()).unwrap_or_else(|_| "<external object>".to_string());
            write!(f, "{:?}", r)
        })
    }
}

impl IntoPy<PyObject> for ExternalObject {
    fn into_py(self, _py: Python<'_>) -> PyObject {
        self.obj
    }
}

