// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

pub fn __py_main() -> Result<(), PyError> {
    println!("{} {}", "Hello".to_string(), "World".to_string());
    print!("{}", "One".to_string());
    print!("{}", "-".to_string());
    print!("{}", "Two".to_string());
    print!("{}", "-".to_string());
    print!("{}", "Three".to_string());
    println!("");
    print!("{}", "No".to_string());
    print!(" ");
    print!("{}", "Newline".to_string());
    print!("{}", " ".to_string());
    println!("{}", "Continued".to_string());
    print!("{}", "Custom".to_string());
    print!("{}", "|".to_string());
    print!("{}", "Sep".to_string());
    print!("{}", "|".to_string());
    print!("{}", "And".to_string());
    print!("{}", "|".to_string());
    print!("{}", "End".to_string());
    print!("{}", "!!!\n".to_string());
    print!("{}", "Multiple".to_string());
    print!("{}", "; ".to_string());
    print!("{}", "Prints".to_string());
    println!("");
    print!("{}", 1);
    print!("{}", ", ".to_string());
    print!("{}", 2);
    print!("{}", ", ".to_string());
    print!("{}", 3);
    println!("");
    Ok(())
}
fn main() -> Result<(), PyError> {
    __py_main()?;

    Ok(())
}
