// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
// csv = { version = "1.1" }
// pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
// pythonize = { version = "0.20" }
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0" }
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<PyError> for pyo3::PyErr {
    fn from(err: PyError) -> Self {
        match err {
            PyError::Exception(s) => pyo3::exceptions::PyException::new_err(s),
            PyError::ValueError(s) => pyo3::exceptions::PyValueError::new_err(s),
            PyError::TypeError(s) => pyo3::exceptions::PyTypeError::new_err(s),
            PyError::KeyError(s) => pyo3::exceptions::PyKeyError::new_err(s),
            PyError::IndexError(s) => pyo3::exceptions::PyIndexError::new_err(s),
            PyError::IOError(s) => pyo3::exceptions::PyOSError::new_err(s),
        }
    }
}

pub trait Drawable {
    fn draw(&self) -> Result<String, PyError>;
}

pub trait CircleTrait {
    fn draw(&self) -> Result<String, PyError>;
}

pub trait SquareTrait {
    fn draw(&self) -> Result<String, PyError>;
}

#[derive(Clone, Debug)]
struct Circle {
    radius: i32,
}

impl Circle {
    fn new(radius: i32) -> Result<Self, PyError> {
        Ok(Self { radius: radius })
    }
}

impl CircleTrait for Circle {
    fn draw(&self) -> Result<String, PyError> {
        return Ok(format!("Circle({})", self.radius));
    }
}


#[derive(Clone, Debug)]
struct Square {
    side: i32,
}

impl Square {
    fn new(side: i32) -> Result<Self, PyError> {
        Ok(Self { side: side })
    }
}

impl SquareTrait for Square {
    fn draw(&self) -> Result<String, PyError> {
        return Ok(format!("Square({})", self.side));
    }
}


impl Drawable for Circle {
    fn draw(&self) -> Result<String, PyError> {
        return Ok(format!("Circle({})", self.radius));
    }
    
}

impl Drawable for Square {
    fn draw(&self) -> Result<String, PyError> {
        return Ok(format!("Square({})", self.side));
    }
    
}

fn render(items: Vec<Box<dyn Drawable>>) -> Result<(), PyError> {
    let mut item: &dyn Drawable;

    {
        '__loop_0: for __loop_val in &items {
            item = &**__loop_val;
            println!("{}", item.draw()?);
        }
    }
    Ok(())
}

fn __py_main() -> Result<(), PyError> {
    let shapes: Vec<Box<dyn Drawable>> = vec![Box::new(Circle::new(5)?) as Box<dyn Drawable>, Box::new(Square::new(10)?) as Box<dyn Drawable>];
    render(shapes)?;
    Ok(())
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}



/*
[dependencies]
csv = { version = "1.1" }
pyo3 = { version = "0.20", features = ["abi3-py310", "extension-module"] }
pythonize = { version = "0.20" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
*/
