// Generated by py2rust
#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

fn add(x: i32, y: i32) -> Result<i32, PyError> {
    return Ok((x + y));
}

fn multiply(x: i32, y: i32) -> Result<i32, PyError> {
    return Ok((x * y));
}

fn main() -> Result<(), PyError> {
    let a: i32 = 10;
    let b: i32 = 5;
    let sum_result: i32 = add(a, b)?;
    let product: i32 = multiply(a, b)?;
    println!("{}", sum_result);
    println!("{}", product);
    { 0; return Ok(()); }
}
