// Generated by py2rust
//
// Required dependencies for Cargo.toml:
// [dependencies]
//

#[derive(Debug, Clone)]
pub enum PyError {
    Exception(String),
    ValueError(String),
    TypeError(String),
    KeyError(String),
    IndexError(String),
    IOError(String),
}

impl std::fmt::Display for PyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PyError::Exception(s) => write!(f, "Exception: {}", s),
            PyError::ValueError(s) => write!(f, "ValueError: {}", s),
            PyError::TypeError(s) => write!(f, "TypeError: {}", s),
            PyError::KeyError(s) => write!(f, "KeyError: {}", s),
            PyError::IndexError(s) => write!(f, "IndexError: {}", s),
            PyError::IOError(s) => write!(f, "IOError: {}", s),
        }
    }
}

impl From<std::io::Error> for PyError {
    fn from(err: std::io::Error) -> Self {
        PyError::IOError(err.to_string())
    }
}

impl From<std::num::ParseIntError> for PyError {
    fn from(err: std::num::ParseIntError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

impl From<std::num::ParseFloatError> for PyError {
    fn from(err: std::num::ParseFloatError) -> Self {
        PyError::ValueError(err.to_string())
    }
}

pub enum TryResult<T> {
    Normal,
    Return(T),
    Break,
    Continue,
}

pub fn __py_main() -> Result<(), PyError> {
    let mut i: i32 = 0;

    {
        let __result = (|| -> Result<TryResult<()>, PyError> {
            return Err(PyError::ValueError("inner err".to_string()));
            Ok(TryResult::Normal)
        })();
        match __result {
            Ok(TryResult::Return(v)) => return Ok(v),
            Ok(TryResult::Break) => panic!("break outside loop"),
            Ok(TryResult::Continue) => panic!("continue outside loop"),
            Ok(TryResult::Normal) => {}
            Err(e) => {
                let e = e.clone();
                {
                    let __result = (|| -> Result<TryResult<()>, PyError> {
                        return Err(PyError::Exception("outer err".to_string())); /* warning: cause lost */
                        Ok(TryResult::Normal)
                    })();
                    match __result {
                        Ok(TryResult::Return(v)) => return Ok(v),
                        Ok(TryResult::Break) => panic!("break outside loop"),
                        Ok(TryResult::Continue) => panic!("continue outside loop"),
                        Ok(TryResult::Normal) => {}
                        Err(ex) => {
                            let ex = ex.clone();
                            println!("{}", "caught nested".to_string());
                        }
                    }
                }
            }
        }
    }
    {
        for __i_i in 0..5 {
            i = __i_i;
            {
                let __result = (|| -> Result<TryResult<()>, PyError> {
                    if i == 3 {
                        return Ok(TryResult::Break);
                    }
                    if i == 1 {
                        return Ok(TryResult::Continue);
                    }
                    println!("{}", i);
                    Ok(TryResult::Normal)
                })();
                match __result {
                    Ok(TryResult::Return(v)) => return Ok(v),
                    Ok(TryResult::Break) => break,
                    Ok(TryResult::Continue) => continue,
                    Ok(TryResult::Normal) => {}
                    Err(_) => {
                        0;
                    }
                }
            }
        }
    }
    println!("{}", test_return()?);
    Ok(())
}

pub fn test_return() -> Result<i32, PyError> {
    {
        let __result = (|| -> Result<TryResult<i32>, PyError> {
            return Ok(TryResult::Return((42)));
            Ok(TryResult::Normal)
        })();
        match __result {
            Ok(TryResult::Return(v)) => return Ok(v),
            Ok(TryResult::Break) => panic!("break outside loop"),
            Ok(TryResult::Continue) => panic!("continue outside loop"),
            Ok(TryResult::Normal) => {}
            Err(_) => {
                return Ok(-(1));
            }
        }
    }
    Ok(0)
}

#[cfg(test)]
#[test]
fn _test_wrapper_test_return() {
    test_return().unwrap();
}
fn main() -> Result<(), PyError> {
    __py_main()?;
    Ok(())
}
